<a href="https://colab.research.google.com/github/hermela-tt/SATC_Dialogue_Analytics/blob/main/SATC_Dialogue_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:

# COMMIT - CREATED USING COLAB, INITIAL PROJECT SETUP AND SATC DATASET EXPLORATION


import pandas as pd

#check what files viewable
import os
os.listdir()

# upload file each time, option
#from google.colab import files
# files.upload()

# Load the CSV directly (bc it's already uploaded to google Colab environment files on the left panel)
df = pd.read_csv('SATC_all_lines.csv')


# Quickly print shape and columns without heavy functions,  no buffering
print("Shape (Rows, Columns):", df.shape)
print("Columns:", list(df.columns))


# Show first 3 rows
display(df.head(3))




# CLEANING PRELIMINARY


# missing values across all columns
print("\n Missing Values Per Column")
print(df.isnull().sum())


# check the top 15 unique speakers to see how characters are named
print("\n Top 15 Speakers by Dialogue Count ")


# Replace 'speaker' with your exact column name if it's capitalized differently (e.g., 'Speaker')
print(df["Speaker"].value_counts().head(15))




# drop null - remove rows where there is no character (speaker) or dialogue (line) to clean into a new dataframe (df_clean)
df_clean = df.dropna(subset=["Speaker", "Line"])


print(" \n Original rows: ", len(df))
print("\n Clean rows: ", len(df_clean))




# WHO TALKS THE MOST


speaker_counts = df_clean["Speaker"].value_counts()


dialogue_share = (speaker_counts / speaker_counts.sum() * 100).round(2)


print(dialogue_share.head(10))




# CHECKING TOTAL ROWS AND VALUES


#checking total number of rows by pulling bottom of dataset
df["Unnamed: 0"].tail()


#why does it reset
df["Unnamed: 0"].nunique()


#how many unique values, top 20 rows
df["Unnamed: 0"].head(20)


# how many unique value
df["Unnamed: 0"].nunique()


print ("\n ")
#fixing name inconsitences


# to stop mistakes - waring: A value is trying to be set on a copy of a slice from a DataFrame (Try using .loc[row_indexer,col_indexer] = value instead)
df_clean = df.dropna(subset=["Speaker", "Line"]).copy()
# remove spaces for speakers
df_clean["Speaker"] = df_clean["Speaker"].str.strip()


#are speaker names consistent
df_clean["Speaker"].unique()[:30]




# BEGIN CHARACTER ANALYSIS


# new dataframe for cleaned speaker column (without spaces), call first 15
df_clean["Speaker"].value_counts().head(15)




# COMMIT - REMOVED OLD CODE


# make sure we have a clean, duplicate copy
df_clean = df.copy()
print("Original rows:", len(df))
print("Clean copy rows:", len(df_clean))

# remove rows missing a speaker and line
df_clean = df_clean.dropna(subset=["Speaker", "Line"])

print("Rows after removing missing dialogue:")
print(len(df_clean))
#check mising or overlap (null) total in columns
df_clean.isnull().sum()

# (standardized) dropped index column (#)
df_clean = df_clean.drop(columns=["Unnamed: 0"])

print(df_clean.columns)


# to get total after cleaning new dataset
df_clean.nunique()

# to check on unique episode numbers
df_clean["Episode"].value_counts().sort_index()

# checking on why episodes end at
df_clean["Speaker"].value_counts().head(20)



# COMMIT - CLEAN SATC DATASET AND ANALYZE CHARACTER FREQUENCY

#created new dataframe for the four main characters (based on highest freq on cleaned dataframe)
main_characters = ["Carrie", "Miranda", "Samantha", "Charlotte"]
# copied clean copy for speakers of 4 main characters
df_main = df_clean[df_clean["Speaker"].isin(main_characters)].copy()
# print title before dataset
print("\n Main character rows:", df_main.shape)
df_main.head()

# get values of who talks the most of the 4
df_main["Speaker"].value_counts()

# vocab of the 4 characters (unqiue dialogue lines)
df_main.groupby("Speaker")["Line"].nunique()

#looking at variety of words
from collections import Counter
import re
#for each character, take and join the speaker text from their lines into a string
for character in ["Carrie", "Miranda", "Samantha", "Charlotte"]:
    text = " ".join(df_main[df_main["Speaker"] == character]["Line"].astype(str))

    # Convert to lowercase and keep only words
    words = re.findall(r"\b[a-z']+\b", text.lower())

    # Show the 20 most common words
    print(f"\n{character}")
    print(Counter(words).most_common(20))

#question - dialogue percentages between the top four --- creating a table to highlight mmy findings
speaker_counts = df_main["Speaker"].value_counts()

speaker_table = (
    speaker_counts
    .rename_axis("Character")
    .reset_index(name="Dialogue Lines")
)

speaker_table["% of Main Four Dialogue"] = (
    speaker_table["Dialogue Lines"] /
    speaker_table["Dialogue Lines"].sum() * 100
).round(2)

speaker_table["% of All Dialogue"] = (
    speaker_table["Dialogue Lines"] /
    len(df_clean) * 100
).round(2)

speaker_table

#finding - Carrie accounts for 35.57% of all dialogue and 52.70% amongst the four protagonists, supporting her main character status.

#question - after removing stop words, what words found for top 4 characters and what do they mean

custom_stopwords = {
    "i'm", "it's", "don't", "just", "know", "like",
    "right", "think", "really", "oh", "got", "did",
    "gonna", "can't", "that's", "you're", "he's",
    "i've", "i'll", "we're", "want", "going"
}

print(custom_stopwords)

# remove standard stop words (the, I, and) to explore actual vocab
from collections import Counter
import re
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

#for 4 personas
for character in ["Carrie", "Miranda", "Samantha", "Charlotte"]:
    #true or false, select each characters lines, join into one string
    text = " ".join(
        df_main[df_main["Speaker"] == character]["Line"].astype(str)
    )
    # make joined string into word boundary's, a-z, allowing for abstrophy's, lower case words
    words = re.findall(r"\b[a-z']+\b", text.lower())
    # drop stop and custom stop words
    words = [
        word for word in words
        if word not in ENGLISH_STOP_WORDS
        and word not in custom_stopwords
    ]
    # count and bring 20 most common remaining words
    common_words = Counter(words).most_common(20)
    # skip a line and print characters name before printing their commmon owrds
    print(f"\n{character}")
    print(common_words)


  # custom stop words to avoid basic words, based on prelimainry dropping of basic english standard stop words
custom_stopwords = {
    "i'm", "it's", "don't", "just", "know", "like",
    "right", "think", "really", "oh", "got", "did",
    "gonna", "can't", "that's", "you're", "he's",
    "i've", "i'll", "we're", "want", "going"
}

# COMMIT - REMOVED MISSING DIALOGUE ROWS, STANDARDIZE SPEAKER NAMES,  FIND TOP 4 SATC CHARACTERS FIND TOP 4 SATC CHRACTERS, AND BEGIN DROPPING STOP WORDS

Shape (Rows, Columns): (39999, 6)
Columns: ['Unnamed: 0', 'Season', 'Episode', 'Speaker', 'Line', 'date_job']

,Unnamed: 0,Season,Episode,Speaker,Line,date_job
0,0,1.0,1.0,Carrie,"Once upon a time, an English journalist came t...",NaN
1,1,1.0,1.0,Carrie,Elizabeth was attractive and bright.,NaN
2,2,1.0,1.0,Carrie,Right away she hooked up with one of the city'...,NaN

 Missing Values Per Column
Unnamed: 0        0
Season           10
Episode          11
Speaker         803
Line            788
date_job      39911
dtype: int64

 Top 15 Speakers by Dialogue Count
Speaker
Carrie       13941
Miranda       4780
Samantha      4067
Charlotte     3667
Big           1233
Steve          801
Aidan          703
Aleksandr      511
Trey           382
Stanford       367
Jack           364
Smith          222
Anthony        210
Richard        189
Robert         159
Name: count, dtype: int64

 Original rows:  39999

 Clean rows:  39195
Speaker
Carrie       35.57
Miranda      12.20
Samantha     10.38
Charlotte     9.36
Big           3.15
Steve         2.04
Aidan         1.79
Aleksandr     1.30
Trey          0.97
Stanford      0.94
Name: count, dtype: float64


Original rows: 39999
Clean copy rows: 39999
Rows after removing missing dialogue:
39195
Index(['Season', 'Episode', 'Speaker', 'Line', 'date_job'], dtype='object')

 Main character rows: (26455, 5)

Carrie
[('i', 4079), ('the', 3676), ('a', 3228), ('to', 3058), ('you', 2591), ('and', 2302), ('was', 1881), ('it', 1611), ('that', 1558), ('of', 1432), ('in', 1398), ('my', 991), ('is', 943), ('for', 931), ('me', 909), ("i'm", 885), ('have', 811), ('with', 802), ('what', 748), ('just', 748)]

Miranda
[('i', 1328), ('you', 1108), ('the', 830), ('a', 809), ('to', 804), ('it', 478), ('and', 474), ("i'm", 474), ('that', 373), ('me', 353), ('is', 348), ('my', 345), ('in', 339), ('have', 320), ('this', 308), ('of', 294), ("it's", 284), ('what', 270), ('not', 260), ("don't", 256)]

Samantha
[('i', 1035), ('you', 952), ('a', 763), ('the', 745), ('to', 676), ('and', 442), ('it', 437), ("i'm", 355), ('that', 306), ('is', 296), ('me', 296), ('in', 274), ('my', 263), ('have', 260), ('of', 235), ('what', 233), ('this', 230), ('not', 228), ("it's", 222), ('do', 208)]

Charlotte
[('i', 1053), ('you', 902), ('to', 648), ('the', 615), ('a', 604), ('and', 452), ('it', 391), ('that', 337), ('is', 331), ("i'm", 304), ('have', 296), ("it's", 266), ('my', 252), ('in', 242), ('just', 238), ('me', 232), ('what', 229), ('this', 221), ('not', 205), ('of', 203)]
{'really', "he's", "can't", 'oh', 'gonna', 'right', "i'm", 'just', "you're", 'want', 'got', 'think', "that's", "don't", "it's", 'like', 'did', "i'll", "i've", 'going', 'know', "we're"}

Carrie
[('samantha', 436), ('miranda', 432), ('charlotte', 404), ('new', 389), ('night', 369), ('time', 306), ('good', 282), ('big', 264), ("didn't", 248), ('love', 234), ('thing', 226), ('say', 220), ('later', 217), ('man', 214), ('okay', 205), ('maybe', 196), ('york', 191), ('little', 187), ('day', 180), ('come', 180)]

Miranda
[('steve', 111), ('good', 86), ('time', 81), ('look', 80), ('yeah', 79), ('okay', 79), ('love', 70), ('say', 70), ('come', 67), ('sex', 66), ("didn't", 66), ('guy', 65), ('thing', 65), ('need', 63), ('baby', 62), ('big', 60), ('great', 59), ('sorry', 59), ('god', 59), ('ok', 55)]

Samantha
[('good', 86), ('look', 82), ('sex', 77), ('love', 71), ('fuck', 66), ('man', 64), ('guy', 64), ('honey', 64), ('yes', 63), ('big', 58), ('say', 57), ('time', 56), ('men', 55), ('come', 53), ('fucking', 50), ('need', 47), ('thing', 45), ('samantha', 44), ("i'd", 43), ('little', 43)]

Charlotte
[('love', 95), ('trey', 69), ('good', 65), ('look', 62), ('sorry', 57), ('say', 55), ('baby', 55), ('married', 54), ('stop', 51), ('yes', 48), ('maybe', 47), ('time', 47), ('mean', 46), ('sex', 46), ('okay', 45), ('big', 43), ('god', 43), ('carrie', 42), ('man', 42), ('great', 41)]

In [11]:
import pandas as pd

# Load the SATC dataset from the file that is now visible in Colab
df = pd.read_csv("SATC_all_lines.csv")

# Check that it loaded correctly
print(df.shape)

# Show first 5 rows
df.head()

(39999, 6)

,Unnamed: 0,Season,Episode,Speaker,Line,date_job
0,0,1.0,1.0,Carrie,"Once upon a time, an English journalist came t...",NaN
1,1,1.0,1.0,Carrie,Elizabeth was attractive and bright.,NaN
2,2,1.0,1.0,Carrie,Right away she hooked up with one of the city'...,NaN
3,3,1.0,1.0,Tim,The question remains-- Is this really a compan...,NaN
4,4,1.0,1.0,Carrie,"Tim was 42, a well-liked and respected investm...",NaN

In [12]:
 print(df_clean.shape)

(39195, 5)

In [13]:
print(df_main.shape)

(26455, 5)

In [7]:
import os
os.listdir()

['.config', 'SATC_all_lines.csv', 'sample_data']

In [6]:
from google.colab import files

files.upload()

Saving SATC_all_lines.csv to SATC_all_lines.csv

{'SATC_all_lines.csv': b',Season,Episode,Speaker,Line,date_job\n0,1.0,1.0,Carrie,"Once upon a time, an English journalist came to New York.",\n1,1.0,1.0,Carrie,Elizabeth was attractive and bright.,\n2,1.0,1.0,Carrie,Right away she hooked up with one of the city\'s typically eligible bachelors.,\n3,1.0,1.0,Tim,The question remains-- Is this really a company we want to own? ,\n4,1.0,1.0,Carrie,"Tim was 42, a well-liked and respected investment banker who made about two million a year.",\n5,1.0,1.0,Carrie,"They met one evening, in typical New York fashion at a gallery opening.",\n6,1.0,1.0,Tim,Like it? ,\n7,1.0,1.0,Elizabeth,"Yes, actually. I think it\'s quite interesting. What?",\n8,1.0,1.0,Tim, I feel like I know you from somewhere.,\n9,1.0,1.0,Elizabeth,Doubtful. I only just moved here from London.,\n10,1.0,1.0,Tim,London? Really? That\'s my all-time favorite city.,\n11,1.0,1.0,Elizabeth,- It is?,\n12,1.0,1.0,Tim,Absolutely.,\n13,1.0,1.0,Carrie,It was love at first sight.,\n14,1.0,1.0,Elizabeth,You know I think perhaps I have met you somewhere before.,\n15,1.0,1.0,Carrie,For two weeks they snuggled went to romantic restaurants had wonderful sex and shared their most intimate secrets.,\n16,1.0,1.0,Carrie,One warm spring day he took her to a town house he saw in Sunday\'s New York Times.,\n17,1.0,1.0,Realtor,How \'bout if we start at the top and work our way down? There are four bedrooms upstairs. Do you have any children? ,\n18,1.0,1.0,Tim,Not yet.,\n19,1.0,1.0,Carrie,"That day, Tim popped the question.",\n20,1.0,1.0,Tim,How\'d you like to have dinner with my folks Tuesday night?,\n21,1.0,1.0,Elizabeth,I\'d love to.,\n22,1.0,1.0,Carrie,"On Tuesday, he called with some bad news.",\n23,1.0,1.0,Tim,My mother\'s not feeling very well.,\n24,1.0,1.0,Elizabeth,"Well, gosh, I\'m sorry.",\n25,1.0,1.0,Tim,- Could we take a rain check? ,\n26,1.0,1.0,Elizabeth,- Of course. Tell your mum I hope she feels better.,\n27,1.0,1.0,Carrie,"When she hadn\'t heard from him for two weeks, she called.",\n28,1.0,1.0,Elizabeth,"Tim, it\'s Elizabeth. That\'s an awfully long rain check.",\n29,1.0,1.0,Carrie,He said he was up to his ears and that he\'d call her the next day.,\n30,1.0,1.0,Elizabeth,"He never did call, of course. Bastard.",\n31,1.0,1.0,Carrie,- She told me one day over coffee.,\n32,1.0,1.0,Elizabeth,- I don\'t understand.,\n33,1.0,1.0,Elizabeth,"In England, looking at houses together would have meant something.",\n34,1.0,1.0,Carrie,Then I realized no one had told her about the end of love in Manhattan.,\n35,1.0,1.0,Carrie,"Welcome to the age of ""un-innocence.",\n36,1.0,1.0,Carrie,""" No one has breakfast at Tiffany\'s, and no one has affairs to remember.",\n37,1.0,1.0,Carrie,"Instead, we have breakfast at 7:00 a.m.",\n38,1.0,1.0,Carrie,and affairs we try to forget as quickly as possible.,\n39,1.0,1.0,Carrie,Self-protection and closing the deal are paramount.,\n40,1.0,1.0,Carrie,Cupid has flown the co-op.,\n41,1.0,1.0,Carrie,"How the hell did we get into this mess? There are thousands, maybe tens of thousands of women like this in the city.",\n42,1.0,1.0,Carrie,"We all know them, and we all agree they\'re great.",\n43,1.0,1.0,Carrie,They travel.,\n44,1.0,1.0,Carrie,They pay taxes.,\n45,1.0,1.0,Carrie,They\'ll spend $400 on a pair of Manolo Blahnik strappy sandals.,\n46,1.0,1.0,Carrie,And they\'re alone.,\n47,1.0,1.0,Carrie,It\'s like the riddle of the Sphinx.,\n48,1.0,1.0,Carrie,Why are there so many great unmarried women and no great unmarried men? I explore these sorts of issues in my column and I have terrific sources: my friends.,\n49,1.0,1.0,Peter Mason,"When you\'re a young guy in your 20s, women are controlling the relationship.",\n50,1.0,1.0,Peter Mason,So by the time you\'re an eligible man in your 30s you feel like you\'re being devoured by women.,\n51,1.0,1.0,Peter Mason,"Suddenly, the guys are holding all the chips.",\n52,1.0,1.0,Peter Mason,I call it the mid-30s power flip.,\n53,1.0,1.0,Capote Duncan,It\'s all about age and biology.,\n54,1.0,1.0,Capote Duncan,"I mean, if you want to get married, it\'s to have kids, right? Not with someone older than 35, \'cause you have to have kids right away and that\'s about it.",\n55,1.0,1.0,Capote Duncan,I think these women should just forget about marriage and have a good time.,\n56,1.0,1.0,Miranda,I have a friend who\'d always gone out with extremely sexy guys and just had a good time.,\n57,1.0,1.0,Miranda,"One day she woke up, and she was 41.",\n58,1.0,1.0,Miranda,She couldn\'t get any more dates.,\n59,1.0,1.0,Miranda,She had a complete physical breakdown couldn\'t hold her job and moved back to Wisconsin to live with her mother.,\n60,1.0,1.0,Miranda,Trust me-- this is not a story that makes men feel bad.,\n61,1.0,1.0,Charlotte,Most men are threatened by successful women.,\n62,1.0,1.0,Charlotte,"If you want to get these guys, you have to keep your mouth shut and play by the rules.",\n63,1.0,1.0,Skipper,I totally believe that love conquers all.,\n64,1.0,1.0,Skipper,Sometimes you just have to give it a little space and that\'s exactly what\'s missing in Manhattan-- the space for romance.,\n65,1.0,1.0,Peter Mason,The problem is expectations.,\n66,1.0,1.0,Peter Mason,Older women don\'t want to settle for what\'s available.,\n67,1.0,1.0,Miranda,"By the time you reach your mid-30s you think, ""Why should I settle?"" You know?",\n68,1.0,1.0,Charlotte,"It\'s like the older we get, the more we keep self-selecting down to a smaller and smaller group.",\n69,1.0,1.0,Capote Duncan,What women really want is Alec Baldwin.,\n70,1.0,1.0,Peter Mason,There\'s not one woman in New York who hasn\'t turned down 10 wonderful guys because they were too short or too fat or too poor.,\n71,1.0,1.0,Miranda,"I have been out with some of those guys-- the short, fat, poor ones.",\n72,1.0,1.0,Miranda,It makes absolutely no difference.,\n73,1.0,1.0,Miranda,They are just as self-centered and unappreciative as the good-looking ones.,\n74,1.0,1.0,Peter Mason,"Why don\'t these women just marry a fat guy? Why don\'t they just marry a big, fat tub of lard?",\n75,1.0,1.0,Group,"Happy birthday, dear Miranda Happy birthday to you",\n76,1.0,1.0,Carrie, Another 30-something birthday with a group of unmarried female friends.,\n77,1.0,1.0,Carrie,We would all have preferred a nice celebratory conference call.,\n78,1.0,1.0,Miranda,- You were saying?,\n79,1.0,1.0,Samantha," Look. If you\'re a successful single woman in this city, you have two choices: You can bang your head against the wall and try and find a relationship or you can say ""screw it,"" and just go out and have sex like a man.",\n80,1.0,1.0,Charlotte,- You mean with dildos?,\n81,1.0,1.0,Samantha,"No, I mean without feeling.",\n82,1.0,1.0,Carrie,Samantha was a New York inspiration.,\n83,1.0,1.0,Carrie,A public relations executive she routinely slept with good-looking guys in their 20s.,\n84,1.0,1.0,Samantha,"Remember that guy I was going out with? Oh, God, what was his name?",\n85,1.0,1.0,Group,Drew.,\n86,1.0,1.0,Carrie,- Drew the sex god.,\n87,1.0,1.0,Samantha,- Right.,\n88,1.0,1.0,Samantha,Afterwards? I didn\'t feel a thing.,\n89,1.0,1.0,Samantha,"It was like, ""Hey, babe, gotta go.",\n90,1.0,1.0,Samantha,Catch ya later.,\n91,1.0,1.0,Samantha,""" And I completely forgot about him after that.",\n92,1.0,1.0,Charlotte,But are you sure that isn\'t just \'cause he didn\'t call you? ,\n93,1.0,1.0,Samantha,"Sweetheart, this is the first time in the history of Manhattan that women have had as much money and power as men plus the equal luxury of treating men like sex objects.",\n94,1.0,1.0,Miranda,"Yeah, except men in this city fail on both counts.",\n95,1.0,1.0,Miranda,"I mean, they don\'t want to be in a relationship with you but as soon as you only want them for sex, they don\'t like it.",\n96,1.0,1.0,Miranda,All of a sudden they can\'t perform the way they\'re supposed to.,\n97,1.0,1.0,Samantha,- That\'s when you dump them.,\n98,1.0,1.0,Carrie,"- Ladies, are we really that cynical? What about romance? ",\n99,1.0,1.0,Charlotte,Yeah.,\n100,1.0,1.0,Samantha,Who needs it?,\n101,1.0,1.0,Miranda,"It\'s like that guy, Jeremiah, the poet.",x\n102,1.0,1.0,Miranda,"I mean, the sex was incredible.",\n103,1.0,1.0,Miranda,"But then he wanted to read me his poetry and go out to dinner and the whole chat bit, and I\'m like, ""Let\'s not even go there.",\n104,1.0,1.0,Charlotte,""" What are you saying? That you\'re just going to give up on love? - That\'s sick.",\n105,1.0,1.0,Carrie,"- No, no, no.",\n106,1.0,1.0,Carrie,"Believe me the right guy comes along, and you two here, this whole thing-- - right out the window.",\n107,1.0,1.0,Charlotte,- That\'s right! ,\n108,1.0,1.0,Samantha,Listen to me! The right guy is an illusion.,\n109,1.0,1.0,Samantha,Start living your lives.,\n110,1.0,1.0,Carrie,So you think it\'s really possible to pull off this whole women-having-sex-like-men thing?,\n111,1.0,1.0,Samantha,You\'re forgetting The Last Seduction.,\n112,1.0,1.0,Carrie,- You\'re obsessed with that movie.,\n113,1.0,1.0,Miranda,"Okay, Linda Fiorentino fucking that guy up against the chain-link fence.",\n114,1.0,1.0,Samantha,"And never having one of those ""Oh, my God, what have I done?"" epiphanies.",\n115,1.0,1.0,Charlotte,I hated that movie.,\n116,1.0,1.0,Carrie,Was it true? Were women in New York really giving up on love and throttling up on power? What a tempting thought.,\n117,1.0,1.0,Stanford Blatch,I\'m beginning to think the only place one can still find love and romance in New York is the gay community.,\n118,1.0,1.0,Stanford Blatch,It\'s straight love that\'s become closeted.,\n119,1.0,1.0,Carrie,Stanford Blatch was one of my closest friends.,\n120,1.0,1.0,Carrie,"He owned a talent agency and, at the moment, was down to a single client.",\n121,1.0,1.0,Carrie,"So, are you telling me that you\'re in love? ",\n122,1.0,1.0,Stanford Blatch,"How could I possibly sustain a relationship? You know Derek takes up like, a thousand percent of my time.",\n123,1.0,1.0,Carrie,Don\'t you think that\'s a bit obsessive?,\n124,1.0,1.0,Stanford Blatch,Carrie I\'m a passionate person. His career is all I care about.,\n125,1.0,1.0,Stanford Blatch,"When that\'s under control, then I can concentrate on my personal life.",\n126,1.0,1.0,Carrie,"Stanford, he\'s an underwear model.",\n127,1.0,1.0,Stanford Blatch,With a billboard in Times Square.,\n128,1.0,1.0,Stanford Blatch,"Oh, my God.",\n129,1.0,1.0,Stanford Blatch,Don\'t turn around.,\n130,1.0,1.0,Stanford Blatch,The loathe of your life is at the bar.,\n131,1.0,1.0,Carrie,It was Kurt Harrington a mistake I made when I was 26 and 29 and 31.,\n132,1.0,1.0,Stanford Blatch,"Carrie, don\'t even go there.",\n133,1.0,1.0,Carrie,What? Do you think I\'m a masochist? - The man is scum.,\n134,1.0,1.0,Stanford Blatch,- Good.,\n135,1.0,1.0,Stanford Blatch,Because I don\'t have the patience to clean up this mess for the fourth time.,\n136,1.0,1.0,Carrie,Will you relax? I don\'t have a shred of feeling left.,\n137,1.0,1.0,Stanford Blatch,Thank God.,\n138,1.0,1.0,Carrie,"Now, if you\'ll excuse me, I have to visit the ladies\' room.",\n139,1.0,1.0,Carrie,It was true.,\n140,1.0,1.0,Carrie,I no longer felt a thing for Kurt.,\n141,1.0,1.0,Carrie,"After all these years, I finally saw him for what he was: a self-centered, withholding creep who was still the best sex I ever had in my life.",\n142,1.0,1.0,Carrie,"However, I did have a little experiment in mind.",\n143,1.0,1.0,Carrie,Kurt. Wow. What are you doin\' here?,\n144,1.0,1.0,Kurt Harrington," Hey, babe.",\n145,1.0,1.0,Kurt Harrington,"- God, you look gorgeous.",\n146,1.0,1.0,Carrie,- Thanks.,\n147,1.0,1.0,Carrie,"So, how\'s life? ",\n148,1.0,1.0,Kurt Harrington,Not bad. Can\'t complain.,\n149,1.0,1.0,Carrie,"You? Oh, you know, just writing the column.",\n150,1.0,1.0,Carrie,The usual.,\n151,1.0,1.0,Carrie,"So, you seeing anyone special?",\n152,1.0,1.0,Kurt Harrington,Not really. You? ,\n153,1.0,1.0,Carrie,"Oh, just a couple guys.",\n154,1.0,1.0,Carrie,"- Well, you look good, though.",\n155,1.0,1.0,Kurt Harrington,- So do you.,\n156,1.0,1.0,Carrie,So what are you doing later?,\n157,1.0,1.0,Kurt Harrington,I thought you weren\'t talking to me for the rest of your life.,\n158,1.0,1.0,Carrie,Who said anything about talking?,\n159,1.0,1.0,Kurt Harrington,"What do you say to my place, 3:00?",\n160,1.0,1.0,Carrie,Alright. See ya there.,\n161,1.0,1.0,Stanford Blatch,Are you out of your mind? What the hell do you think you\'re doing?,\n162,1.0,1.0,Carrie,"Oh, calm down.",\n163,1.0,1.0,Carrie,It\'s research.,\n164,1.0,1.0,Carrie,"Oh, God.",\n165,1.0,1.0,Carrie,"Oh, Kurt.",\n166,1.0,1.0,Carrie,Kurt was just like I remembered-- better-- because this time there would be none of that messy emotional attachment.,\n167,1.0,1.0,Kurt Harrington,All righty.,\n168,1.0,1.0,Kurt Harrington,My turn.,\n169,1.0,1.0,Carrie,"Oh, sorry.",\n170,1.0,1.0,Carrie,I have to go back to work.,\n171,1.0,1.0,Kurt Harrington,What? Are you kiddin\'? You\'re serious? ,\n172,1.0,1.0,Carrie,"Oh, yeah. Completely.",\n173,1.0,1.0,Carrie,But I\'ll give you a call.,\n174,1.0,1.0,Carrie,Maybe we can do it again sometime.,\n175,1.0,1.0,Kurt Harrington,"Yeah, but-- ",\n176,1.0,1.0,Carrie,"As I began to get dressed, I realized that I\'d done it.",\n177,1.0,1.0,Carrie,I\'d just had sex like a man.,\n178,1.0,1.0,Carrie,"I left feeling powerful, potent and incredibly alive.",\n179,1.0,1.0,Carrie,I felt like I owned this city.,\n180,1.0,1.0,Carrie,Nothing and no one could get in my way.,\n181,1.0,1.0,Carrie,"- Number one, he\'s very handsome.",\n182,1.0,1.0,Big,- There ya go.,\n183,1.0,1.0,Carrie,"Number two, he\'s not wearing a wedding ring.",\n184,1.0,1.0,Carrie,"Number three, he knows I carry textured Trojans with a reservoir tip.",\n185,1.0,1.0,Carrie,Thanks a lot.,\n186,1.0,1.0,Big,Anytime.,\n187,1.0,1.0,Carrie,"Later that night, Skipper met me for coffee and confessed a shocking intimate secret.",\n188,1.0,1.0,Carrie,Thank you.,\n189,1.0,1.0,Skipper,"Do you know that it has been, like, a year? ",\n190,1.0,1.0,Carrie,Really? I don\'t understand that.,\n191,1.0,1.0,Carrie,You\'re such a nice guy.,\n192,1.0,1.0,Skipper,That\'s the problem.,\n193,1.0,1.0,Skipper,"I\'m too nice, you know? I\'m a romantic.",\n194,1.0,1.0,Skipper,I just have so much feeling.,\n195,1.0,1.0,Carrie,Are you sure you\'re not gay? ,\n196,1.0,1.0,Skipper,No! I\'m sensitive and I don\'t objectify women.,\n197,1.0,1.0,Skipper,"You know, most guys, when they meet a girl the first thing that they see is-- - You know-- - ",\n198,1.0,1.0,Carrie,Pussy?,\n199,1.0,1.0,Skipper,"Oh, God! Oh! I hate that word.",\n200,1.0,1.0,Skipper,Don\'t you have any friends that you can hook me up with?,\n201,1.0,1.0,Carrie,They\'re too old for you.,\n202,1.0,1.0,Skipper,- I like older women.,\n203,1.0,1.0,Carrie,Maybe.,\n204,1.0,1.0,Carrie,- Maybe my friend Miranda.,\n205,1.0,1.0,Skipper,- When? ,\n206,1.0,1.0,Carrie,Tomorrow night.,\n207,1.0,1.0,Carrie,"We\'re all going downtown to this club, Chaos.",\n208,1.0,1.0,Skipper,Great.,\n209,1.0,1.0,Skipper,Don\'t tell her I\'m nice.,\n210,1.0,1.0,Carrie,Miranda was gonna hate Skipper.,\n211,1.0,1.0,Carrie,She\'d think he was mocking her with his sweet nature and decide he was an asshole the way she had decided all men were assholes.,\n212,1.0,1.0,Carrie,- Hello? -,\n213,1.0,1.0,Charlotte,"Hey, Carrie, it\'s Charlotte.",\n214,1.0,1.0,Carrie,"- Hey, sweetie.",\n215,1.0,1.0,Charlotte,- Hey.,\n216,1.0,1.0,Charlotte,"Look, I can\'t meet you guys for dinner tomorrow night because I have an amazing date.",\n217,1.0,1.0,Carrie,With who? ,\n218,1.0,1.0,Charlotte,Capote Duncan. He\'s supposedly some big shot in the publishing world.,x\n219,1.0,1.0,Charlotte,- Do you know him? - ,\n220,1.0,1.0,Carrie,"Did I know him? He was one of the city\'s most notoriously ""un-gettable"" bachelors.",\n221,1.0,1.0,Charlotte,"Wait, don\'t even answer that question because, frankly, I don\'t care.",\n222,1.0,1.0,Charlotte,And another thing.,\n223,1.0,1.0,Charlotte,I\'m not buying any of that women-having-sex-like-men crap.,\n224,1.0,1.0,Carrie,I didn\'t tell her about my afternoon of cheap and easy sex and how good it felt.,\n225,1.0,1.0,Carrie,All right.,\n226,1.0,1.0,Carrie,Fine.,\n227,1.0,1.0,Carrie,"Have a good time, and promise to tell me everything.",\n228,1.0,1.0,Charlotte,"Well, if you\'re lucky.",\n229,1.0,1.0,Charlotte,- Bye.,\n230,1.0,1.0,Carrie,- All right.,\n231,1.0,1.0,Carrie,Bye.,\n232,1.0,1.0,Carrie,Friday night at Chaos.,\n233,1.0,1.0,Carrie,"It was just like that bar in ""Cheers"" where everybody knows your name except here they were likely to forget it five minutes later.",\n234,1.0,1.0,Carrie,Hi.,\n235,1.0,1.0,Carrie,"Still, it was the creme de la creme of New York whipped into a frenzy.",\n236,1.0,1.0,Carrie,Sometimes you got a souffle sometimes cottage cheese.,\n237,1.0,1.0,Miranda,It is like a model bomb exploded in this room tonight.,\n238,1.0,1.0,Miranda,Is there a woman here aside from me who weights more than a hundred pounds? ,\n239,1.0,1.0,Skipper,"I know, it\'s like ""Undereaters Anonymous.",\n240,1.0,1.0,Miranda,""" That\'s funny, Skippy.",\n241,1.0,1.0,Skipper,- Skipper.,\n242,1.0,1.0,Miranda,- I have this theory that men secretly hate pretty girls because they rejected them in school.,\n243,1.0,1.0,Skipper,Right.,\n244,1.0,1.0,Skipper,"But if you\'re not part of the ""Beauty Olympics"" you can still become a very interesting person.",\n245,1.0,1.0,Miranda,Are you saying that I\'m not pretty enough? ,\n246,1.0,1.0,Skipper,"No, no, no. Of course you are.",\n247,1.0,1.0,Miranda,"So, ipso f acto, I can\'t be interesting? Women fall into one of two categories: beautiful and boring or homely and interesting, is that it?",\n248,1.0,1.0,Skipper,"No, that\'s not what I meant.",\n249,1.0,1.0,Miranda,Excuse me.,\n250,1.0,1.0,Miranda,Is this your hand on my knee? ,\n251,1.0,1.0,Skipper,No.,\n252,1.0,1.0,Miranda,"Let\'s just keep \'em where I can see \'em, all right? Well, I guess you must find me beautiful.",\n253,1.0,1.0,Miranda,- Or interesting.,\n254,1.0,1.0,Carrie,"- I was about to rescue Skipper from an increasingly hopeless situation, when suddenly-- ",\n255,1.0,1.0,Kurt Harrington,"Lucky me, twice in one week.",\n256,1.0,1.0,Carrie,"Well, I don\'t know if you\'re going to be getting that lucky.",\n257,1.0,1.0,Kurt Harrington,"You know, I was really pissed off the way you left the other day.",\n258,1.0,1.0,Carrie,- You were?,\n259,1.0,1.0,Kurt Harrington,"Yeah. Then I thought, how great! You finally understand the kind of relationship I want and now we can have sex without commitment.",\n260,1.0,1.0,Carrie,Yeah.,\n261,1.0,1.0,Carrie,Right.,\n262,1.0,1.0,Carrie,Sure.,\n263,1.0,1.0,Carrie,I guess.,\n264,1.0,1.0,Carrie,"- So when I feel like it, I\'ll call you.",\n265,1.0,1.0,Kurt Harrington,"- Yeah, please.",\n266,1.0,1.0,Kurt Harrington,Whenever you feel like it.,\n267,1.0,1.0,Kurt Harrington,"If I\'m alone, I\'m all yours.",\n268,1.0,1.0,Carrie,Right.,\n269,1.0,1.0,Kurt Harrington,I like this new you.,\n270,1.0,1.0,Kurt Harrington,Call me.,\n271,1.0,1.0,Carrie,Yup.,\n272,1.0,1.0,Carrie,I didn\'t understand.,\n273,1.0,1.0,Carrie,"Did all men secretly want their women promiscuous and emotionally detached? And if I was really having sex like a man, why didn\'t I feel more in control? ",\n274,1.0,1.0,Samantha,You see that guy? He\'s the next Donald Trump except he\'s younger and much better looking.,\n275,1.0,1.0,Carrie,Hi.,\n276,1.0,1.0,Samantha,- You know him? ,\n277,1.0,1.0,Carrie,No. I\'ve never seen him in my life.,\n278,1.0,1.0,Samantha,"He usually dates models, but, hey, I\'m as good-looking as a model plus I own my own business.",\n279,1.0,1.0,Carrie,Samantha had the kind of deluded self-confidence that caused men like Ross Perot to run for president and it usually got her what she wanted.,\n280,1.0,1.0,Samantha,"Well, if you\'re not gonna hit on him, I will.",\n281,1.0,1.0,Carrie,And there she went-- off to take her best shot with Big.,\n282,1.0,1.0,Carrie,"Meanwhile, C